#!/usr/bin/env python3
"""Store indexes for Memory/Long-Term/.

    memory_index.py report        list every store whose _index.yaml is empty or misses entries
    memory_index.py fill          write a mechanical _index.yaml into every EMPTY one (never
                                  overwrites a hand-written index)
    memory_index.py fill <Store>  the same for one store
    memory_index.py sync          bring every index in line with its store, at any depth:
                                  append an entry for each missing top-level file or folder and
                                  each uncovered nested file, in that index's own style, and drop
                                  entries whose path no longer exists; other entries untouched
    memory_index.py lint          report only; exit 1 if any index is empty, missing, uncovered
                                  or stale, or a wiki longterm_ref is broken

Coverage, at any depth: a file is covered when its own path, or the path of a folder above it,
is the value of a `path:`, `file:`, `folder:` or `tone_file:` entry (or a `name:` entry inside a
`files:`, `contents:` or `folders:` list). A person index (`people:`)
also covers every file in a folder that holds a listed file. Entries under `archived:`, `moved:`
or `retired:` record history and are never checked. LukeatronWiki indexes pages by slug, so it
is checked only by the wiki-ref test.

Descriptions are taken from the file itself (its first heading and first prose line), never
written freehand, so a generated index can be trusted and later hand-improved.
"""
import datetime
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3] / "Memory/Long-Term"
TEXT = {".md", ".txt", ".yaml", ".yml", ".csv", ".json", ".html"}
KIND = {".png": "image", ".jpg": "image", ".jpeg": "image", ".webp": "image", ".svg": "svg",
        ".pdf": "pdf", ".db": "database", ".sqlite": "database", ".docx": "docx"}


def entries(store):
    return sorted(p for p in store.iterdir() if not p.name.startswith((".", "_")))


def quote(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def first_lines(path):
    title, line = "", ""
    try:
        body = path.read_text(errors="ignore")
    except OSError:
        return title, line
    in_front = body.startswith("---")
    for raw in body.splitlines()[1 if in_front else 0:]:
        text = raw.strip()
        if in_front:
            if text == "---":
                in_front = False
            elif text.startswith("title:") and not title:
                title = text[6:].strip().strip("\"'")
            continue
        if not text or text.startswith(("<!--", "|", "---", "```", "![")):
            continue
        if text.startswith("#"):
            title = title or text.lstrip("#").strip()
            continue
        line = text.lstrip("-*> ").replace("**", "").strip()
        break
    return title, (line[:157] + "…") if len(line) > 160 else line


def count_items(path, kind):
    rows = path.read_text(errors="ignore").splitlines()
    if kind == "list":
        n = sum(1 for r in rows if r.lstrip().startswith(("- ", "* ", "+ ")) or r.lstrip()[:3].rstrip(". ").isdigit())
    else:
        n = max(0, sum(1 for r in rows if r.lstrip().startswith("|")) - 2)
    return f"{n} {'items' if kind == 'list' else 'rows'}"


def describe(path):
    if path.is_dir():
        files = [p for p in path.rglob("*") if p.is_file() and not p.name.startswith(".")]
        return {"kind": "folder", "title": path.name, "description": f"{len(files)} files"}
    ext = path.suffix.lower()
    if ext in TEXT:
        title, line = first_lines(path)
        stem = path.name.split(".")[0].replace("_", " ").replace("-", " ")
        kind = path.name.split(".")[-2] if path.name.count(".") >= 2 else ext.lstrip(".")
        kind = kind or ext.lstrip(".")
        if kind in ("list", "table"):
            line = count_items(path, kind)
        return {"kind": kind, "title": title or stem, "description": line}
    return {"kind": KIND.get(ext, ext.lstrip(".") or "file"),
            "title": path.stem.replace("_", " "), "description": ""}


def render(store):
    today = datetime.date.today().isoformat()
    lines = [f"# Memory/Long-Term/{store.name}/_index.yaml",
             f"last_updated: {today}",
             f"store: {quote(store.name)}",
             "note: >",
             "  Generated by System/Tools/memory-index/memory_index.py from each file's own first",
             "  heading and first line. Improve descriptions by hand; the tool never overwrites.",
             "contents:"]
    items = entries(store)
    if not items:
        lines[-1] = "contents: []"
    for path in items:
        info = describe(path)
        lines.append(f"  - path: {quote(path.name)}")
        lines.append(f"    kind: {info['kind']}")
        lines.append(f"    title: {quote(info['title'])}")
        if info["description"]:
            lines.append(f"    description: {quote(info['description'])}")
    return "\n".join(lines) + "\n"


def stores():
    return sorted(p for p in ROOT.iterdir() if p.is_dir() and not p.name.startswith("."))


def report():
    for store in stores():
        index = store / "_index.yaml"
        text = index.read_text() if index.exists() else ""
        if not text.strip():
            print(f"EMPTY    {store.name}")
            continue
        missing = [p.name for p in entries(store) if p.name not in text]
        if missing:
            print(f"MISSING  {store.name}: {', '.join(missing)}")


LIST_KEYS = ("files", "contents", "folders", "people")
ENTRY = re.compile(r'^(\s*)(- )?(path|file|folder|tone_file|name):\s*(.+?)\s*$')
HISTORY_KEYS = ("archived", "moved", "retired")
SLUG_INDEXED = ("LukeatronWiki",)


def unquote(value):
    value = value.split(" #", 1)[0].strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return value.strip().strip("/").removeprefix("./")


def listed_entries(lines):
    """Yield (line number, value, is_list_item) for every path-like entry outside history blocks."""
    top = None
    for i, line in enumerate(lines):
        if line and not line.startswith((" ", "#", "-")):
            top = line.split(":", 1)[0]
        match = ENTRY.match(line)
        if match and match.group(3) == "name" and top not in ("files", "contents", "folders"):
            continue
        if match and top not in HISTORY_KEYS and "<" not in match.group(4):
            yield i, unquote(match.group(4)), bool(match.group(2))


def files_in(store):
    for path in sorted(store.rglob("*")):
        rel = path.relative_to(store)
        if path.is_file() and not any(part.startswith((".", "_")) for part in rel.parts):
            yield rel.as_posix()


def analyse(store, text):
    """Return (missing top-level paths, uncovered nested files, stale (line, value, is_item))."""
    lines = text.split("\n")
    found = list(listed_entries(lines))
    listed = {value for _, value, _ in found}
    if "people:" in text:
        listed |= {value.rsplit("/", 1)[0] for value in list(listed) if "/" in value}
    missing = [p for p in entries(store)
               if p.name not in listed and not any(v.startswith(p.name + "/") for v in listed)]
    if store.name in SLUG_INDEXED:
        return [p for p in missing if p.name not in text], [], []
    missing_names = {p.name for p in missing}

    def covered(rel):
        parts = rel.split("/")
        return any("/".join(parts[:i]) in listed for i in range(1, len(parts) + 1))

    uncovered = [rel for rel in files_in(store)
                 if "/" in rel and rel.split("/", 1)[0] not in missing_names and not covered(rel)]
    roots = (store, ROOT, ROOT.parent.parent)
    stale = [(i, value, item) for i, value, item in found
             if value and not any((base / value).exists() for base in roots)]
    return missing, uncovered, stale


def blocks(lines):
    found = {}
    for i, line in enumerate(lines):
        key = line.split(":", 1)[0]
        if key in LIST_KEYS and not line.startswith((" ", "#")):
            end = next((j for j in range(i + 1, len(lines))
                        if lines[j] and not lines[j].startswith((" ", "#", "-"))), len(lines))
            while end > i + 1 and not lines[end - 1].strip():
                end -= 1
            item = next((lines[j].strip()[2:].split(":", 1)[0] for j in range(i + 1, end)
                         if lines[j].lstrip().startswith("- ")), None)
            found[key] = (i, end, item)
    return found


def entry_lines(path, item_key):
    info = describe(path)
    name = path.name + ("/" if path.is_dir() and item_key == "folder" else "")
    out = [f"  - {item_key}: {quote(name)}", f"    kind: {info['kind']}", f"    title: {quote(info['title'])}"]
    if info["description"]:
        out.append(f"    description: {quote(info['description'])}")
    out.append(f"    added: {datetime.date.today().isoformat()}")
    return out


def drop_entry(lines, i):
    """Remove the list item starting at line i, with every more-indented line under it."""
    indent = len(lines[i]) - len(lines[i].lstrip())
    end = i + 1
    while end < len(lines) and (not lines[end].strip() or len(lines[end]) - len(lines[end].lstrip()) > indent):
        end += 1
    del lines[i:end]


def append_entry(lines, path, store):
    """Append one entry for `path` (a file or folder inside `store`) in the index's own style."""
    found = blocks(lines)
    key = "folders" if path.is_dir() and "folders" in found else next(
        (k for k in ("files", "contents") if k in found), None)
    if key is None:
        if "people" in found:
            return False
        lines += ["contents:"]
        found = blocks(lines)
        key = "contents"
    start, end, item = found[key]
    if lines[start].strip().endswith("[]"):
        lines[start] = key + ":"
    item = item or ("folder" if key == "folders" else "path")
    entry = entry_lines(path, item)
    rel = path.relative_to(store).as_posix() + ("/" if path.is_dir() and item == "folder" else "")
    entry[0] = f"  - {item}: {quote(rel)}"
    lines[end:end] = entry
    return True


def sync():
    added = dropped = 0
    for store in stores():
        index = store / "_index.yaml"
        if not index.exists() or not index.read_text().strip():
            continue
        text = index.read_text()
        missing, uncovered, stale = analyse(store, text)
        if store.name in SLUG_INDEXED or not (missing or uncovered or stale):
            continue
        lines = text.rstrip("\n").split("\n")
        for i, value, item in sorted(stale, reverse=True):
            if item:
                drop_entry(lines, i)
                dropped += 1
                print(f"- {store.name}/{value}")
        for path in missing + [store / rel for rel in uncovered]:
            if append_entry(lines, path, store):
                added += 1
                print(f"+ {store.name}/{path.relative_to(store).as_posix()}")
        today = datetime.date.today().isoformat()
        lines = [f"{l.split(':')[0]}: {today}" if l.startswith(("last_updated:", "updated:")) else l for l in lines]
        index.write_text("\n".join(lines) + "\n")
    print(f"{added} entries added, {dropped} stale entries dropped")


def lint():
    problems = 0
    for store in stores():
        index = store / "_index.yaml"
        text = index.read_text() if index.exists() else ""
        if not text.strip():
            print(f"EMPTY     {store.name}"); problems += 1
            continue
        missing, uncovered, stale = analyse(store, text)
        for label, items in (("MISSING", [p.name for p in missing]), ("UNCOVERED", uncovered),
                             ("STALE", [value for _, value, _ in stale])):
            if items:
                print(f"{label:<9} {store.name}: {', '.join(items[:6])}{' …' if len(items) > 6 else ''}")
                problems += 1
    print("✓ every store index is complete and current" if not problems else f"✗ {problems} index problems; run `sync`")
    nodes = ROOT / "LukeatronWiki/Nodes"
    broken = []
    for node in sorted(nodes.glob("*.md")) if nodes.exists() else []:
        in_refs = False
        for line in node.read_text(errors="ignore").split("---")[1].splitlines():
            if line.startswith("longterm_refs:"):
                in_refs = True
            elif in_refs and line.startswith("  -"):
                target = line[3:].strip().strip("\"'").split(" :: ")[-1].strip()
                if target and not (ROOT / target).exists():
                    broken.append(f"{node.name} → {target}")
            elif in_refs and line and not line.startswith(" "):
                in_refs = False
    for item in broken:
        print(f"BROKEN   wiki {item}")
    print("✓ every wiki longterm_ref resolves" if not broken else f"✗ {len(broken)} broken wiki refs")
    return problems + len(broken)


def fill(only=None):
    written = 0
    for store in stores():
        if only and store.name != only:
            continue
        index = store / "_index.yaml"
        if index.exists() and index.read_text().strip():
            continue
        index.write_text(render(store))
        print(f"wrote {index.relative_to(ROOT.parent.parent)}")
        written += 1
    print(f"{written} indexes written")


if __name__ == "__main__":
    args = sys.argv[1:]
    if args[:1] == ["report"]:
        report()
    elif args[:1] == ["sync"]:
        sync()
    elif args[:1] == ["lint"]:
        sys.exit(1 if lint() else 0)
    elif args[:1] == ["fill"]:
        fill(args[1] if len(args) > 1 else None)
    else:
        sys.exit(__doc__)
