"""Generate the TEST copy's fixture tree — Phase 4 Step 5 fake data.

This is the ONE place the test copy's data is authored. `Memory/Medium-Term/`
under `fixtures/lukeatron_root/` is fully regenerated by running this file —
never hand-edited — so the fixture can be rebuilt at any time without anyone
re-typing a `registry.md` by hand (System/Skillbank/PersonalResearch/
!AppDevelopment/phase4-refactor.md STEP 5: "a seed/fake-data script").

Run:  python3 seed_fixture.py
Then: LUKEATRON_ROOT=<this dir>/fixtures/lukeatron_root python3 build_faces.py
      (or just `./run_build.sh`, which sets that for you.)

Every date below is computed relative to *today* (not hardcoded to one
calendar date), so re-running this script keeps the "due inside seven days"
and "overdue" edge cases true on whatever day it is next run.

Nothing here is plausible on purpose: project titles, people, dates. This
tree is never read by the real app (_template/) and the real app's Memory/
is never read by this one — the two are wired apart by LUKEATRON_ROOT
(paths.py), not by a second mechanism invented here.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIXTURE_ROOT = HERE / "fixtures" / "lukeatron_root"
PROJECTS_DIR = FIXTURE_ROOT / "Memory" / "Medium-Term" / "Projects"
MINOR_TASKS_DIR = FIXTURE_ROOT / "Memory" / "Medium-Term" / "MinorTasks"

TODAY = date.today()

CONTEXTS = ("Church", "Personal Productivity", "Teaching", "Personal Research")

# Fictional people — never a real name, never Luke's actual collaborators.
WAITING_ON = (
    "Captain Obvious", "A. Nonymous", "Sir Reads-a-Lot", "Baron von Redtape",
    "Lady Gadget", "The Right Honourable Nobody", "Professor Placeholder",
    "Ms. Perpetual Motion", "Reverend Hypothetical", "Dr. Wanda Ideas",
)


def slugify(title: str) -> str:
    s = title.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def iso(d: date | None) -> str:
    return d.isoformat() if d else "—"


# ---------------------------------------------------------------------------
# Next Actions rows
# ---------------------------------------------------------------------------


@dataclass
class Row:
    action: str
    owner: str = "—"
    kind: str | None = "unshaped"   # None => omit the Kind cell text (legacy)
    effort: str | None = "—"
    tokens: str | None = "—"
    status: str = "☐ Open"
    state: str = "⚪ undefined"
    due: str = "—"


@dataclass
class Project:
    id: str
    title: str
    context: str
    rows: list[Row]
    legacy_columns: bool = False   # FK-08: no Kind/Effort/Tokens columns at all
    updated_days_ago: int = 6
    wake: date | None = None

    @property
    def slug(self) -> str:
        return slugify(self.title)

    @property
    def dir_name(self) -> str:
        return f"{self.id}-{self.slug}"

    @property
    def rel_registry_path(self) -> str:
        return f"Memory/Medium-Term/Projects/{self.dir_name}/registry.md"


# ---------------------------------------------------------------------------
# The eight signature edge-case projects (see phase4-refactor.md / the task
# brief this seed script was written against for what each one proves).
# ---------------------------------------------------------------------------

SIGNATURE_PROJECTS: list[Project] = [
    Project(
        id="FK-01", title="Rename the Moon", context="Personal Research",
        rows=[
            Row("Decide what the far side gets called", kind="unshaped"),
            Row(
                "A new naming proposal arrives from the Committee of Owls",
                owner="Committee of Owls", kind="incoming",
                due=iso(TODAY + timedelta(days=12)),
            ),
        ],
    ),  # mind project WITH open kind-2/5 tasks
    Project(
        id="FK-02", title="Alphabetize the Ocean", context="Personal Productivity",
        rows=[
            Row("Sort the Pacific before the Atlantic", owner="Luke", kind="mine",
                status="☑ Done", state="—"),
        ],
    ),  # mind project with NO open tasks at all (its one row is closed)
    Project(
        id="FK-03", title="Debug the Weather", context="Teaching",
        rows=[
            Row("Reproduce Tuesday's rain on a clear day", owner="Luke", kind="mine",
                effort="🔨 an hour", tokens="some", state="🟠 your move",
                due=iso(TODAY + timedelta(days=3))),
        ],
    ),  # due inside seven days
    Project(
        id="FK-04", title="Negotiate Peace With the Printer", context="Church",
        rows=[
            Row("Draft the printer's terms of surrender", owner="Agent", kind="hand-over",
                effort="⚡ minutes", tokens="little", state="⚪ undefined",
                due=iso(TODAY - timedelta(days=10))),
        ],
        updated_days_ago=37,  # also exercises FR-10 stale-handover (>14 days)
    ),  # overdue
    Project(
        id="FK-05", title="Compose a Symphony for Kazoos", context="Personal Research",
        rows=[
            Row("Score the second movement", owner="Luke", kind="mine",
                effort="🏔️ a session", tokens="plenty", state="🟠 your move", due="—"),
        ],
    ),  # a project with demand but no dates at all
    Project(
        id="FK-06", title="Draft a Constitution for Ants", context="Personal Productivity",
        rows=[
            Row("Wait for the colony to ratify Article 1", owner="Captain Obvious",
                kind="waiting", state="🔵 waiting",
                due=iso(TODAY - timedelta(days=40))),  # overdue date on a kind-1 row —
            # outline must still read "none": FR-17 only ever looks at kind 3/4.
            Row("Wait for the queen's veto on Article 2", owner="A. Nonymous",
                kind="waiting", state="🔵 waiting"),
        ],
    ),  # every open task is kind 1 — outline "none" whatever its dates
    Project(
        id="FK-07", title="Reverse-Engineer a Sandwich", context="Teaching",
        rows=[
            Row(
                "Compile `Bread|Cheese|Pickle` stack order (decide layering)",
                owner="Luke", kind="mine", effort="🔨 an hour", tokens="some",
                state="🟠 your move", due=iso(TODAY + timedelta(days=45)),
            ),
        ],
    ),  # FR-2a: a literal pipe inside backticks in the Action cell
    Project(
        id="FK-08", title="Patent the Wheel (Again)", context="Church",
        rows=[Row("File the paperwork before someone else reinvents it", owner="Luke",
                  status="☐ Open", due="—")],
        legacy_columns=True,
    ),  # legacy shape: no Kind/Effort/Tokens columns at all — must still parse
]

# ---------------------------------------------------------------------------
# Filler projects — bulk the board to ~40 and push every kind's count up
# ("in quantity", not one occurrence each). Deterministic, not random, so a
# re-run is a no-op diff except for the today-relative due dates above.
# ---------------------------------------------------------------------------

FILLER_TITLES = [
    "Convince Pigeons to Unionize", "Build a Ladder to Narnia",
    "Teach Toast to Land Butter-Side Up", "Host a Ted Talk for Houseplants",
    "Translate Cat Meows Into Latin", "Audit the Bermuda Triangle",
    "Un-invent the Snooze Button", "Map the Sock Drawer Multiverse",
    "Franchise the Tooth Fairy", "Write a Sequel to Silence",
    "Teach Fish to Whistle", "Standardize the Metric Cloud",
    "Recruit a Union for Garden Gnomes", "Sponsor the Loch Ness Monster's Gap Year",
    "Optimize the Bermuda Onion", "Build a Time Machine (Slowly)",
    "Digitize the Ouija Board", "Onboard a New Species of Houseplant",
    "Trademark the Colour Beige", "Launch a Podcast About Silence",
    "Teach the Roomba to Meditate", "Draft the Sequel to the Wheel",
    "Certify Clouds as Load-Bearing", "Rebrand Mondays as Optional",
    "Migrate the Sock Drawer to the Cloud", "Crowdfund a Second Moon",
    "Localize Silence Into Klingon", "Benchmark the Speed of Gossip",
    "Retire the Number Thirteen", "Compile a Dictionary of Shrugs",
    "Audit the Tooth Fairy's Books", "Deploy a Weather Balloon of Opinions",
]
assert len(FILLER_TITLES) == 32

_KIND_CYCLE = ("waiting", "unshaped", "mine", "hand-over", "incoming")

_ACTION_TEMPLATE = {
    "waiting": "Wait for {who} to weigh in on {title}",
    "unshaped": "Work out what {title} would even mean",
    "mine": "Draft the plan for {title}",
    "hand-over": "Hand off the particulars of {title}",
    "incoming": "A proposal about {title} lands",
}

# A spread of due offsets for the filler kind-3/4 rows, cycling so the board
# carries some near, some far, some none — without colliding with the
# specifically-labelled FK-03 (this week) / FK-04 (overdue) / FK-05 (none)
# cases above.
_DEMAND_DUE_OFFSETS = (60, None, 90, 21, 180, None, 30)


def build_filler_projects() -> list[Project]:
    projects: list[Project] = []
    for i, title in enumerate(FILLER_TITLES):
        context = CONTEXTS[i % len(CONTEXTS)]
        kind = _KIND_CYCLE[i % len(_KIND_CYCLE)]
        who = WAITING_ON[i % len(WAITING_ON)]
        action = _ACTION_TEMPLATE[kind].format(who=who, title=title)

        if kind == "waiting":
            row = Row(action, owner=who, kind="waiting", state="🔵 waiting")
        elif kind == "unshaped":
            row = Row(action, owner="—", kind="unshaped", state="⚪ undefined")
        elif kind == "mine":
            offset = _DEMAND_DUE_OFFSETS[i % len(_DEMAND_DUE_OFFSETS)]
            due = iso(TODAY + timedelta(days=offset)) if offset is not None else "—"
            effort, tokens = (("⚡ minutes", "little"), ("🔨 an hour", "some"),
                              ("🏔️ a session", "plenty"))[i % 3]
            row = Row(action, owner="Luke", kind="mine", effort=effort, tokens=tokens,
                      state="🟠 your move", due=due)
        elif kind == "hand-over":
            row = Row(action, owner="Agent", kind="hand-over", state="⚪ undefined")
        else:  # incoming
            arrives_luke = i % 2 == 0
            who_arrives = "Luke" if arrives_luke else who
            row = Row(action, owner=who_arrives, kind="incoming", state="⚪ undefined",
                      due=iso(TODAY + timedelta(days=3 + (i % 20))))

        idx = i + 9  # FK-01..FK-08 already used
        projects.append(Project(id=f"FK-{idx:02d}", title=title, context=context, rows=[row]))
    return projects


ALL_PROJECTS: list[Project] = [*SIGNATURE_PROJECTS, *build_filler_projects()]
assert len(ALL_PROJECTS) == 40, f"expected 40 projects, got {len(ALL_PROJECTS)}"


# ---------------------------------------------------------------------------
# Rendering — registry.md / _tracking.yaml / MinorTasks/queue.md
# ---------------------------------------------------------------------------


def render_registry(p: Project) -> str:
    frontmatter = (
        "---\n"
        f'project: "{p.slug}"\n'
        f'id: "{p.id}"\n'
        f'title: "{p.title}"\n'
        f"context: {p.context}\n"
        "status: Active\n"
        "---\n"
    )
    if p.legacy_columns:
        header = "| # | Action | Owner | Status | Due |\n|---|--------|-------|--------|-----|\n"
        lines = [
            f"| {n} | {r.action} | {r.owner} | {r.status} | {r.due} |"
            for n, r in enumerate(p.rows, start=1)
        ]
    else:
        header = (
            "| # | Action | Owner | Kind | Effort | Tokens | Status | State | Due |\n"
            "|---|--------|-------|------|--------|--------|--------|-------|-----|\n"
        )
        lines = [
            f"| {n} | {r.action} | {r.owner} | {r.kind} | {r.effort} | {r.tokens} | "
            f"{r.status} | {r.state} | {r.due} |"
            for n, r in enumerate(p.rows, start=1)
        ]
    return frontmatter + "\n# ✅ Next Actions\n\n" + header + "\n".join(lines) + "\n"


def render_tracking(projects: list[Project]) -> str:
    lines = [
        "# GENERATED by seed_fixture.py — do not hand-edit. Re-run the script instead.",
        "# Obviously-fake TEST fixture: every id, title and date below is invented.",
        "projects:",
    ]
    for p in projects:
        updated = TODAY - timedelta(days=p.updated_days_ago)
        wake = iso(p.wake) if p.wake else ""
        lines += [
            f"  - id: {p.id}",
            f"    project: {p.slug}",
            f'    title: "{p.title}"',
            f"    context: {p.context}",
            "    status: Active",
            '    state: "⚪ undefined"',
            '    waiting_on: ""',
            f'    wake: "{wake}"',
            f"    created: {(TODAY - timedelta(days=200)).isoformat()}",
            f"    updated: {updated.isoformat()}",
            f"    path: {p.rel_registry_path}",
            "",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Depot — Memory/Medium-Term/MinorTasks/queue.md
#
# stores.read_queue keeps only open rows (☐/◐, FR-5); model.build_depot maps
# Impact: High -> kind 3 (mine), Impact: Low -> kind 4 (an agent can take it).
# The ticker's own rest threshold is `--tick-rest-below: 8` (tokens.css) — a
# lane at or above that many jobs rolls, below it it just sits there. Ten of
# each impact keeps both lanes rolling with room to spare, comfortably more
# than the eight-job floor the task calls for.
# ---------------------------------------------------------------------------

_DEPOT_HIGH_TASKS = [
    "Teach the office plant to file its own expenses",
    "Decide whether Tuesday counts as a weekday this week",
    "Negotiate a truce with the stapler",
    "Rename every folder called 'final'",
    "Confirm the ceiling fan's opinion on the agenda",
    "Draft a rebuttal to the microwave's beeping",
    "Approve the kettle's promotion to management",
    "Settle the dispute between the two staplers",
    "Sign off on the houseplant's expansion plan",
    "Ratify the new coffee-to-tea exchange rate",
]
_DEPOT_LOW_TASKS = [
    "File the paperwork the paperwork generated",
    "Reply to the pigeon's union enquiry",
    "Archive last decade's to-do list",
    "Update the sock drawer's terms of service",
    "Water the office cactus (again, still fake)",
    "Forward the moon's rebranding memo",
    "Log the printer's grievance",
    "Close the loop on the loop that never closed",
    "Catalogue every shrug on file",
    "Refile the tooth fairy's expense report",
]
_DEPOT_SOURCES = ("Luke", *WAITING_ON)


def render_queue() -> str:
    lines = [
        "# GENERATED by seed_fixture.py — do not hand-edit. Re-run the script instead.",
        "# TEST fixture — Minor Tasks depot queue, obviously invented.",
        "",
        "| # | Task | Source | Impact | Status | State | Wake/Due | Notes |",
        "|---|------|--------|--------|--------|-------|----------|-------|",
    ]
    n = 1
    for i, task in enumerate(_DEPOT_HIGH_TASKS):
        source = _DEPOT_SOURCES[i % len(_DEPOT_SOURCES)]
        lines.append(f"| {n} | {task} | {source} | High | ☐ Open | 🟢 on track | — | test fixture |")
        n += 1
    for i, task in enumerate(_DEPOT_LOW_TASKS):
        source = _DEPOT_SOURCES[(i + 3) % len(_DEPOT_SOURCES)]
        lines.append(f"| {n} | {task} | {source} | Low | ☐ Open | 🟢 on track | — | test fixture |")
        n += 1
    # One closed row, to prove FR-5's "open rows only" still holds in the fixture.
    lines.append(f"| {n} | Already handled by a very fast agent | Agent | Low | ☑ Done | — | — | closed on purpose |")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Write-out
# ---------------------------------------------------------------------------


def main() -> None:
    if FIXTURE_ROOT.exists():
        shutil.rmtree(FIXTURE_ROOT)
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    MINOR_TASKS_DIR.mkdir(parents=True, exist_ok=True)
    (FIXTURE_ROOT / "Outbox").mkdir(parents=True, exist_ok=True)

    for p in ALL_PROJECTS:
        project_dir = PROJECTS_DIR / p.dir_name
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "registry.md").write_text(render_registry(p), encoding="utf-8")

    (PROJECTS_DIR / "_tracking.yaml").write_text(render_tracking(ALL_PROJECTS), encoding="utf-8")
    (MINOR_TASKS_DIR / "queue.md").write_text(render_queue(), encoding="utf-8")

    print(f"seed_fixture.py: wrote {len(ALL_PROJECTS)} projects under {PROJECTS_DIR}")
    print(f"seed_fixture.py: wrote {MINOR_TASKS_DIR / 'queue.md'}")
    print(f"seed_fixture.py: LUKEATRON_ROOT for this fixture is {FIXTURE_ROOT}")


if __name__ == "__main__":
    main()
