#!/usr/bin/env python3
"""usage — summarise how Lukeatron is used, from Claude Code's own session transcripts. No Claude call.

Reads ~/.claude/projects/*Lukeatron*/*.jsonl on this Mac and rewrites this Mac's week sections of
Memory/Long-Term/Logs/usage.md (other Macs' sections are kept). One section per ISO week (Melbourne time):
  sessions, prompts      sessions with a prompt from Luke that week, and the prompts
  skills                 skills loaded (Skill tool, or a SKILL.md read), with counts
  hooks                  hook messages that blocked a turn, by hook
  denied                 tool calls refused by Luke or the permission classifier, by tool
  corrections            Luke's prompts that correct Claude, ≤140 chars, with the skill active at the time
Sessions that touch the pastoral log or sealed paths contribute counts only, never text.

Usage:
  usage.py [--days 14] [--out PATH] [--projects DIR]
  --days  rewrite every week touched by transcripts modified in the last N days (first run: --days 400)
"""
import argparse
import json
import os
import re
import socket
import subprocess
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

MELBOURNE = ZoneInfo("Australia/Melbourne")
ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "Memory" / "Long-Term" / "Logs" / "usage.md"
SKILL_PATH = re.compile(r"(![A-Za-z][\w-]*)/SKILL\.md")
SEALED = re.compile(r"Pastoral_Notes|!PastoralNote|_sealed\.yaml|--sealed|--pastoral")
CORRECTION = re.compile(
    r"^(no\b|nope|don'?t|do not|stop|wrong|actually|that'?s not|not what|instead|undo|revert|why did you|you (didn'?t|forgot|missed))"
    r"|\b(i said|i asked|i told you|not what i|you were (meant|supposed) to)\b", re.I)
DENIED = ("Permission for this action was denied", "The user doesn't want to proceed", "User rejected", "The user declined")
EXCERPT = 140
HEADER = """# usage.md — how Lukeatron is used, one section per ISO week per Mac (Melbourne time).
# Generated by System/Tools/usage/usage.py from Claude Code transcripts; never hand-edit. Read by !Improve.
"""


def mac_name() -> str:
    try:
        return subprocess.run(["scutil", "--get", "ComputerName"], capture_output=True, text=True, timeout=5).stdout.strip() or socket.gethostname()
    except (OSError, subprocess.SubprocessError):
        return socket.gethostname()


def week_of(stamp: str) -> str | None:
    try:
        when = datetime.fromisoformat(stamp.replace("Z", "+00:00")).astimezone(MELBOURNE)
    except (ValueError, AttributeError):
        return None
    year, week, _ = when.isocalendar()
    return f"{year}-W{week:02d}"


def week_start(week: str) -> datetime:
    year, number = week.split("-W")
    return datetime.fromisocalendar(int(year), int(number), 1).replace(tzinfo=MELBOURNE)


def prompt_text(content) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text")
    return ""


def tool_result_text(block) -> str:
    content = block.get("content")
    if isinstance(content, list):
        return " ".join(c.get("text", "") for c in content if isinstance(c, dict))
    return content if isinstance(content, str) else ""


def blank():
    return {"sessions": set(), "prompts": 0, "skills": Counter(), "hooks": Counter(), "denied": Counter(), "corrections": []}


def read_session(path: Path, weeks: dict, wanted: set) -> None:
    records = []
    with path.open(encoding="utf-8", errors="replace") as stream:
        for raw in stream:
            try:
                records.append(json.loads(raw))
            except ValueError:
                continue
    sealed = any(SEALED.search(json.dumps(r.get("message", ""))) for r in records)
    tools, active, session = {}, "-", path.stem
    for record in records:
        week = week_of(record.get("timestamp", ""))
        if week not in wanted:
            continue
        stats = weeks[week]
        message = record.get("message") or {}
        content = message.get("content") if isinstance(message, dict) else None
        if record.get("type") == "assistant" and isinstance(content, list):
            for block in content:
                if not isinstance(block, dict) or block.get("type") != "tool_use":
                    continue
                tools[block.get("id")] = block.get("name", "?")
                given = block.get("input") or {}
                name = given.get("skill") if block.get("name") == "Skill" else None
                if not name:
                    hit = SKILL_PATH.search(str(given.get("file_path") or given.get("command") or ""))
                    name = hit.group(1) if hit else None
                if name:
                    stats["skills"][name] += 1
                    active = name
        elif record.get("type") == "user":
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "tool_result":
                        text = tool_result_text(block)
                        if text.startswith(DENIED):
                            stats["denied"][tools.get(block.get("tool_use_id"), "?")] += 1
            text = prompt_text(content).strip()
            if text.startswith("Stop hook feedback:") or "hook blocking error" in text[:200]:
                stats["hooks"][text.split(":", 1)[1].strip().split(":")[0][:60] if ":" in text else "hook"] += 1
            elif (record.get("origin") or {}).get("kind") == "human" and text:
                stats["prompts"] += 1
                stats["sessions"].add(session)
                if text.startswith("[Request interrupted by user"):
                    stats["corrections"].append(("interrupted", active))
                elif CORRECTION.search(text[:300]):
                    excerpt = "(sealed session; text withheld)" if sealed else " ".join(text.split())[:EXCERPT]
                    stats["corrections"].append((excerpt, active))


def render(week: str, mac: str, stats: dict) -> str:
    skills = ", ".join(f"{n} {c}" for n, c in stats["skills"].most_common()) or "none"
    hooks = ", ".join(f"{n} {c}" for n, c in stats["hooks"].most_common()) or "none"
    denied = ", ".join(f"{n} {c}" for n, c in stats["denied"].most_common()) or "none"
    lines = [f"## {week} · {mac}",
             f"- sessions {len(stats['sessions'])} · prompts {stats['prompts']}",
             f"- skills: {skills}",
             f"- hooks that blocked: {hooks}",
             f"- denied: {denied}",
             f"- corrections ({len(stats['corrections'])}):"]
    lines += [f"  - [{skill}] {text}" for text, skill in stats["corrections"]]
    return "\n".join(lines) + "\n"


def merge(out: Path, mac: str, sections: dict) -> None:
    kept = {}
    if out.exists():
        for chunk in re.split(r"(?m)^(?=## \d{4}-W\d{2} · )", out.read_text(encoding="utf-8")):
            head = re.match(r"## (\d{4}-W\d{2}) · (.+)\n", chunk)
            if head:
                kept[(head.group(1), head.group(2))] = chunk.rstrip("\n") + "\n"
    for week, text in sections.items():
        kept[(week, mac)] = text
    body = "\n".join(kept[key] for key in sorted(kept, key=lambda k: (k[0], k[1]), reverse=True))
    out.write_text(HEADER + "\n" + body, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--days", type=int, default=14)
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--projects", type=Path, default=Path.home() / ".claude" / "projects")
    args = parser.parse_args()
    files = [f for d in args.projects.glob("*Lukeatron*") if d.is_dir() for f in d.glob("*.jsonl")]
    recent = datetime.now(timezone.utc).timestamp() - args.days * 86400
    wanted = set()
    for f in files:
        if f.stat().st_mtime >= recent:
            with f.open(encoding="utf-8", errors="replace") as stream:
                for raw in stream:
                    hit = re.search(r'"timestamp":"([^"]+)"', raw)
                    week = week_of(hit.group(1)) if hit else None
                    if week:
                        wanted.add(week)
    if not wanted:
        return 0
    earliest = min(week_start(w) for w in wanted).timestamp()
    weeks = defaultdict(blank)
    for f in sorted(files):
        if f.stat().st_mtime >= earliest:
            read_session(f, weeks, wanted)
    mac = mac_name()
    merge(args.out, mac, {w: render(w, mac, s) for w, s in weeks.items() if s["prompts"] or s["skills"]})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
